name: ulda
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.18
  - pytorch=1.13.1
  - tensorboard=2.12.1
  - numpy=1.25.2
  - matplotlib=3.7.2
  - pillow=9.4.0
  - scikit-learn=1.3.0
  - torchvision=0.14.1
  - pip
  - pip:
    - pickle5==0.0.12
    - tqdm==4.66.1
    - ftfy==6.1.1
    - wandb==0.15.11
    - regex==2023.8.8
    - git+https://github.com/openai/CLIP.git
